### ISSUE TITLE
raise an error when read a path on win10.

### ISSUE THREAD

**Issue by bs111** [shpaker/winregistry#3]
I want to read the excel install path from the regedit.
using :
from winregistry import WinRegistry as Reg
reg = Reg()
path = r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\excel.exe\Path"
>>> reg.read_key(path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python37\lib\site-packages\winregistry\winregistry.py", line 110, in read_key
    handle = self._get_handle(key, winreg.KEY_READ, key_wow64_32key)
  File "D:\Python37\lib\site-packages\winregistry\winregistry.py", line 171, in _get_handle
    key_handle = winreg.OpenKey(self.root_handle, path, 0, access)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
>>>

![image](https://user-images.githubusercontent.com/38519076/65478078-eb088c00-deba-11e9-90a4-aa57756014f4.png)

operate system:
win 10 pro
Python 3.7.4
winregistry    0.8.3

**Comment by bs111** [comment]
please  i should use path as 
path = r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\excel.exe"
